default_language_version:
    python: python3.11
repos:
-   hooks:
    -   exclude: ^.*\.md$
        id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   args:
        - --branch
        - master
        - --branch
        - main
        - --branch
        - production
        id: no-commit-to-branch
    -   args:
        - --fix=lf
        id: mixed-line-ending
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-toml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
-   hooks:
    -   id: seed-isort-config
    repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
-   hooks:
    -   id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
-   hooks:
    -   entry: isort
        id: isort
        language: system
        name: isort
        require_serial: true
        types:
        - python
    -   entry: black
        id: black
        language: system
        name: black
        require_serial: true
        types:
        - python
    -   entry: pylint
        id: pylint
        language: system
        name: pylint
        require_serial: true
        types:
        - python
    -   args:
        - src/
        - tests/
        entry: mypy
        id: mypy
        language: system
        name: mypy
        pass_filenames: false
        require_serial: true
        types:
        - python
    -   args:
        - -a
        entry: pre-commit-update
        id: pre-commit-update
        language: python
        name: pre-commit-update
        pass_filenames: false
    repo: local
-   hooks:
    -   args:
        - -r
        - requirements/common.txt
        - -r
        - requirements/dev.txt
        - --no-deps
        - --ignore-vuln
        - GHSA-w596-4wvx-j9j6
        id: pip-audit
    repo: https://github.com/pypa/pip-audit
    rev: v2.8.0
