version: "3.8"

services:
  juice_shop:
    image: bkimminich/juice-shop
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    networks:
      - custom_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: local-jenkins
    restart: unless-stopped
    user: root
    hostname: juice_shop.playright.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/jaksa.milanovic/projects/personal/async_playwright_juice_shop:/app
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      custom_network:
        aliases:
          - juice_shop.playright.jenkins

volumes:
  jenkins_home:

networks:
  custom_network:
    driver: bridge
